onlineAuction/onlineAuction/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [

	url(r'^signup/', include('signup.urls')),
	url(r'^portal/', include('portal.urls')),
    url(r'^admin/', admin.site.urls),
url(r'^captcha/', include('captcha.urls')),

]

onlineAuction/portal/urls.py
from django.conf.urls import url

from . import views

app_name = 'portal'

urlpatterns = [

    url(r'^adminPage/$', views.AdminIndexView.as_view(), name='adminPage'),
    url(r'delete/(?P<id>\d+)/$', views.AdminIndexView.deleteUser, name='delete'),
    url(r'ban/(?P<id>\d+)/$', views.AdminIndexView.banUser, name='ban'),

    url(r'showArticles/(?P<userid>\d+)/deleteArticle/(?P<id>\d+)/$', views.ArticleView.deleteArticle, name='delete'),
    url(r'showArticles/(?P<id>\d+)/$', views.ArticleView.as_view(), name='showArticles'),

    url(r'activeArticles/$', views.ActiveBidView.as_view(), name='activeArticles'),

    url(r'recentArticles/$', views.RecentBidView.as_view(), name='recentArticles'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^RegForm/$', views.RegForm.as_view(), name='RegForm'),
    url(r'^UserShowArticle/$', views.UserShowArticles.as_view(), name='userArticles'),
    url(r'^UserShowArticle/EditArticles/(?P<a_id>\d+)/$', views.EditArticle.as_view(), name='editArticles'),
    url(r'^activeArticles/BidPage/(?P<a_id>\d+)/$', views.Bid.as_view(), name='Bid'),
    url(r'^activeArticles/BidPage/SoldPage/(?P<a_id>\d+)/$', views.Bid.sold, name='Bid'),
    url(r'^SoldBids/$', views.BidsSoldView.as_view(), name='soldArticles'),
    url(r'^WonBids/$', views.BidsWonView.as_view(), name='wonArticles'),

]

onlineAuction/signup/urls.py
from django.conf.urls import url,include

from . import views


app_name = 'signup'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signUpPage/$', views.Signup.as_view(), name='signUpPage'),
    url(r'^LoginForm/$', views.LoginForm.as_view(), name='LoginForm'),
    url(r'^VisaForm/$', views.VisaForm.as_view(), name='VisaForm'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^resetpassword/$', views.PasswordRecover.as_view(), name='PasswordRecover'),
    url(r'^passwordchange/(?P<getlink>\w{0,50})/$', views.PasswordChanger.as_view(), name='PasswordChanger')



    #url(r'^login/$', views.login, name='login'),
    #url(r'^visa/$', views.visaReg, name='visaReg'),
]

onlineAuction/portal/models.py
from django.db import models
from signup import models as userdetails
from channels import Group

# Create your models here.
class banned_user(models.Model):
    userid=models.IntegerField()
    


def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.article.userid.id, instance.article.id,ext)
    return '/'.join(['portal/static/portal/article_images', filename])

class articlereg(models.Model):
    def __str__(self):
        return str(self.id)
    userid=models.ForeignKey(userdetails.UserDetail)
    timestart=models.DateTimeField()
    articlename=models.CharField(max_length=40)
    status = models.CharField(max_length = 20 , default= "inactive")
    category=models.CharField(max_length=40)
    desc=models.CharField(max_length=150)
    minbid=models.FloatField(default=0.0)
    private = models.BooleanField(default = False)
    
class privateusers(models.Model):
    article = models.ForeignKey(articlereg)
    user = models.ForeignKey(userdetails.UserDetail)
    status = models.CharField(max_length = 20 , default= "inactive")

class articleimage(models.Model):
    def __str__(self):
        return str(self.image).split('/')[-1]
    article = models.ForeignKey(articlereg)
    image = models.ImageField(upload_to=content_file_name,default='article_images/'+str(id)+'.jpg')

class bids(models.Model):
    userid=models.ForeignKey(userdetails.UserDetail)
    articleid=models.ForeignKey(articlereg)
    highestbid=models.FloatField(default=0.0)

onlineAuction/portal/forms.py
from django import forms
from .models import *
from signup.models import UserDetail
class RegForm(forms.Form):#user form pre build class

    timestart=forms.DateTimeField(widget=forms.widgets.DateTimeInput(attrs={'placeholder':'YYYY-MM-DD HH:MM:SS', 'type':'datetime-local'}),label="Start date and time:")
    articlename=forms.CharField(max_length=40,label="Article Name:")
    Choices=(('Book','Book'),('Vehicle','Vehicle'),('Coin or Stamp','Coin or Stamp'),('Antique','Antique'),
             ('Electronics','Electronics'),('Others','Others'))
    category=forms.ChoiceField(choices=Choices)
    desc = forms.CharField(max_length=150, label="Description:")
    minbid = forms.FloatField(min_value=0, label="Minimum bid:",
                            widget=forms.widgets.NumberInput(attrs={'onkeypress':'checkHigest(this)','onkeyup':'checkHigest(this)'}))
    Users = []
    for names in UserDetail.objects.all():
        tup = (names.name ,names.name)
        Users.append(tup)
    private = forms.BooleanField(initial = False, required = False, widget=forms.widgets.CheckboxInput(attrs={'onclick':'hide(this)'}))
    Select_Users = forms.MultipleChoiceField(required = False, widget = forms.CheckboxSelectMultiple, choices = Users)
    image=forms.ImageField()


class EditRegForm(forms.Form):#user form pre build class
    timestart=forms.DateTimeField(widget=forms.widgets.DateTimeInput(attrs={'placeholder':'YYYY-MM-DD HH:MM:SS', 'type':'datetime-local'}),label="Start date and time:")
    articlename=forms.CharField(max_length=40,label="Article Name:")
    Choices=(('Book','Book'),('Vehicle','Vehicle'),('Coin or Stamp','Coin or Stamp'),('Antique','Antique'),
             ('Electronics','Electronics'),('Others','Others'))
    category=forms.ChoiceField(choices=Choices)
    desc=forms.CharField(max_length=150,label="Description:")
    Users = []
    for names in UserDetail.objects.all():
        tup = (names.name ,names.name)
        Users.append(tup)
    private = forms.BooleanField(initial = False, required = False, widget=forms.widgets.CheckboxInput(attrs={'onclick':'hide(this)'}))
    Select_Users = forms.MultipleChoiceField(required = False, widget = forms.CheckboxSelectMultiple, choices = Users)
    minbid=forms.FloatField(min_value=0,label="Minimum bid:")
    image=forms.ImageField()

class BidPrice(forms.Form):
     highestbid = forms.FloatField(min_value=0.0)

onlineAuction/portal/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone, dateparse
# Create your views here.
from datetime import datetime, timedelta
from signup.models import UserDetail
from portal.models import articlereg
from portal.models import banned_user
from django.conf import settings
from django.core.mail import send_mail, send_mass_mail
from .forms import *

from django.contrib import messages



def isadmin(request):
    if 'adminSession' in request.session:
        if request.session['adminSession'] == True:
            return True
        else:
            return False
    else:
        return False


class AdminIndexView(generic.TemplateView):
    template_name = 'portal/adminPage.html'

    def get(self, request, *args, **kwargs):
        try:
            if isadmin(request):
                context = {'details': UserDetail.objects.all()}
                return render(request, self.template_name, context)
            else:
                messages.error(request,"You are not authorised.")
                return HttpResponseRedirect(reverse('portal:index'))
        except:
            pass

    def deleteUser(request, id):
        if isadmin(request):
            b = UserDetail.objects.get(pk=id)
            b.delete()
            messages.success(request, "User deleted successfully")
            return HttpResponseRedirect(reverse('portal:adminPage'))
        else:
            messages.error(request, "You are not authorised.")
            return HttpResponseRedirect(reverse('portal:index'))

    def banUser(request, id):
        if isadmin(request):
            if banned_user.objects.filter(userid=id).exists():
                pass
            else:
                ob = banned_user(userid=id)
                ob.save()
                messages.success(request, "User banned")
            return HttpResponseRedirect(reverse('portal:adminPage'))
        else:
            messages.error(request, "You are not authorised.")
            return HttpResponseRedirect(reverse('portal:index'))

class ArticleView(generic.TemplateView):
    template_name = 'portal/adminPageShowArticles.html'

    def get(self, request, id, *args, **kwargs):
        try:
            if isadmin(request):
                context = {'details': articlereg.objects.filter(userid=id)}
                return render(request, self.template_name, context)
            else:
                messages.error(request, "You are not authorised.")
                return HttpResponseRedirect(reverse('portal:index'))
        except:
            pass

    def deleteArticle(request, userid, id):
        if isadmin(request) or (('inSession' in request.session) and request.session['inSession'] == True):
            b = articlereg.objects.get(pk=id)
            if isadmin(request)==False and (b.timestart<timezone.now()):
                messages.error(request, "Ended or active bids cannot be deleted")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                try:
                    b.delete()
                    messages.success(request, "Article deleted")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                except:
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        else:
            messages.error(request, "You are not authorised.")
            return HttpResponseRedirect(reverse('portal:index'))



class ActiveBidView(generic.TemplateView):
    template_name = 'portal/activeArticles.html'

    def get(self, request, *args, **kwargs):
        try:
            if (('inSession' in request.session) and request.session['inSession'] == True) or isadmin(request):
                quer = UserDetail.objects.get(pk=request.session['userID'])
                articles = articlereg.objects.all()
                active_articles = []
                now = timezone.now()
                for a in articles:
                    endtime = a.timestart + timedelta(hours=1)
                    if now >= a.timestart and now < endtime:
                        active_articles.append(a.id)
                context = {'userName': quer.name, 'active': articlereg.objects.filter(id__in=active_articles)}
                return render(request, self.template_name, context)
            else:
                messages.error(request, "Login or signup to proceed.")
                return HttpResponseRedirect(reverse('portal:index'))
        except:
            pass



class RecentBidView(generic.TemplateView):
    template_name = 'portal/recentArticles.html'

    def get(self, request, *args, **kwargs):
        try:
            if (('inSession' in request.session) and request.session['inSession'] == True) or isadmin(request):
                quer = UserDetail.objects.get(pk=request.session['userID'])
                articles = articlereg.objects.all()
                recent_bids = []
                now = timezone.now()
                for a in articles:
                    if a.timestart < (now - timedelta(hours=1)) and a.timestart > (now - timedelta(days=1, hours=1)):
                        recent_bids.append(a.id)
                        a.status = "sold"
                        a.save()
                context = {'userName': quer.name, 'bid': bids.objects.filter(articleid__in=recent_bids)}
                return render(request, self.template_name, context)
            else:
                messages.error(request, "Login or signup to proceed.")
                return HttpResponseRedirect(reverse('portal:index'))
        except:
            pass



























class IndexView(generic.TemplateView):
    template_name = 'portal/index.html'

    def get(self, request, *args, **kwargs):
        try:
            if 'userID' in request.session and request.session['userID'] != None:
                quer = UserDetail.objects.get(pk=request.session['userID'])
                arts = privateusers.objects.all()
                articles = []
                now = timezone.now()
                emptyInv = 0
                emptyInt = 0
                for art in arts:
                    endtime = art.article.timestart + timedelta(hours=1)
                    if now >= art.article.timestart and now < endtime:
                        if(art.user == quer):
                            articles.append(art.article)
                            emptyInv = 1
                arts = articlereg.objects.filter(category = quer.interests)
                interest = []
                now = timezone.now()
                for art in arts:
                    endtime = art.timestart + timedelta(hours=1)
                    if now >= art.timestart and now < endtime:
                        interest.append(art)
                        emptyInt = 1

                context = {'userName': quer.name, 'article': articles, 'emptyInv':emptyInv, 'interest':interest,'emptyInt':emptyInt}
                return render(request, self.template_name, context)
            else:
                return HttpResponseRedirect(reverse("signup:LoginForm"))
        except UserDetail.DoesNotExist:
            return HttpResponseRedirect(reverse("signup:LoginForm"))


class RegForm(generic.edit.FormView):
    form_class = RegForm
    template_name = 'portal/articleForm.html'

    def get(self, request, *args, **kwargs):
        try:
            context = {'userName': UserDetail.objects.get(pk=request.session['userID']).name, 'form': self.form_class}
            return render(request, self.template_name, context)
        except:
            return HttpResponseRedirect(reverse('signup:index'))
    def post(self, request, *args, **kwargs):
        try:
            stat = None
            quer = UserDetail.objects.get(pk=request.session['userID'])
            try:
                time = dateparse.parse_datetime(request.POST['timestart'])
            except ValueError:
                messages.error(request,"Enter correct date time values")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            now = datetime.now()
            deltaNow = timedelta(days=int(now.day), hours=int(now.hour), minutes=int(now.minute),
                                 seconds=int(now.second))
            try:
                delta = timedelta(days=int(time.day), hours=int(time.hour), minutes=int(time.minute),
                              seconds=int(time.second))
            except AttributeError:
                messages.error(request, "Enter correct date time values")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            timedif = (delta - deltaNow).seconds
            deltaHour = timedelta(seconds=3600)
            if (time < (now - timedelta(hours=1))):
                messages.error(request, "Enter correct date time.")
                return HttpResponseRedirect(reverse("portal:RegForm"))
            if(delta > deltaNow):
                stat = "inactive"
            elif(delta > deltaNow - deltaHour):
                stat = "active"
            try :
                request.POST['private'] == 'on'
                priv = True
            except:
                priv = False
            art = quer.articlereg_set.create(
                timestart=request.POST['timestart'], articlename=request.POST['articlename'],
                category=request.POST['category'], desc=request.POST['desc'],
                minbid=request.POST['minbid'], status = stat,
                private = priv)
            art.articleimage_set.create(image=request.FILES['image'])
            mailList = []
            USERS = request.POST.getlist('Select_Users')
            if(priv) is True:
                for users in USERS:

onlineAuction/portal/templates/portal/BidArticle.html
{% extends 'portal/base.html' %}
{% load static %}
<html>
<head>


</head>

<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />

{% block content %}
<div class = "container">
    <div id= "header">
        <h1>BID PAGE</h1>
    </div>
    <form method="post">
		{% csrf_token %}
		<div class = "forms">

			<table id = "try">
				
				<tr>
					<td colspan = "6" >
					<img id = "artImg" src="{% static 'portal/article_images/'%}{{bid.articleid.articleimage_set.reverse.0}}" alt="Image">
					</td>
				</tr>
                <tr>
	                <th colspan = "3">Article Name</th>
	                <th colspan = "3">{{ bid.articleid.articlename }}</th>
                </tr>
				<tr>
					<th colspan = "1" align="left">HIGHEST</th>
					<th id="user" colspan = "3" align="center">{{bid.userid.userName}}</th>
					<th id="high" colspan = "2" align="left">{{bid.highestbid}}</th>
				</tr>
				<tr>
	                <th colspan = "3">TIME REMAINING</th>
	                <th colspan = "3" id = "time"></th>
                </tr>
				<tr>
				<th><label for="id_highestbid">Highestbid:</label></th>
				<td>
				<input id="id_highestbid" name="highestbid" step="any" type="number"
						onkeypress = "checkHigest({{bid.highestbid}}, this)"
						onkeyup = "checkHigest({{bid.highestbid}}, this)">
				</td>
				</tr>
				<tr><td colspan = "6" align="center"><input id = "sub" type="submit" value="Submit" onclick="sendmessage()"/></td></tr>
				<tr><td id = "msg" colspan = "6" style = "color:red;"></td></tr>
				<tr><td id = "msg2" colspan = "6" style = "color:red;"></td></tr>
			</table>
		
		</div>

	</form>
</div>

<script >
socket = new WebSocket("ws://" + window.location.host + "/bids/");
socket.onmessage = function(e) {
    var user = document.getElementById("user");
    var high = document.getElementById("high");
    user.innerHTML = e.data.split(",")[0];
    high.innerHTML = parseFloat(e.data.split(",")[1]);


}
var date = new Date("{{bid.articleid.timestart.isoformat}}");
onload();
function load(x)
{
	console.log(date.getMinutes());
	if(x==1)
	{
		window.location.href = "/portal/activeArticles/BidPage/SoldPage/{{bid.articleid.id}}";
	}
}
function checkHigest(check , ele)
{	
	var btn = document.getElementById("sub");
	var msg = document.getElementById("msg");
	if(ele.value <= check)
	{
		btn.disabled = true;
		msg.innerHTML = "Your bid should be more than higest";
	}
	else
	{
		btn.disabled = false;
		msg.innerHTML = ""
	}
}

function onload()
{
	setInterval(timeCalc, 500);
	var btn = document.getElementById("sub");
	var msg = document.getElementById("msg");
	var ele = document.getElementById("id_highestbid");
	console.log()
	if("{{quer.userName}}" == "{{bid.articleid.userid.userName}}")
	{
		btn.disabled = true;
		ele.disabled = true;
		msg.innerHTML = "You Cannot Bid Your Own Article";
	}

}
function timeCalc()
{
	var btn = document.getElementById("sub");
	var msg = document.getElementById("msg2");
	var ele = document.getElementById("id_highestbid");

	var timeShow = document.getElementById("time");

	artTimeMin = date.getMinutes();
	artTimeSec = date.getSeconds();;
	var currentdate = new Date();
	var min = currentdate.getMinutes();
	var sec = currentdate.getSeconds();
	var minGap = min - artTimeMin;
	var secGap = sec - artTimeSec;

	if(minGap < 0)
	{	minGap+=60;}
	if(secGap < 0)
	{	secGap+=60;}
	timeRemainMin = 59 - minGap;
	timeRemainSec = 59 - secGap;
	if(timeRemainMin == 0 && timeRemainSec==0)
		load(1);
	else
		load(0);
	if("{{bid.articleid.status}}" == "sold")
	{
		timeRemainSec=0;
		timeRemainMin=0;
		btn.disabled = true;
		msg.innerHTML = "BID HAS ENDED";
		ele.disabled = true;
	}
	if(timeRemainSec < 10)
	{
		timeShow.innerHTML = timeRemainMin + ":0" + timeRemainSec;
	}
	else
	{
		timeShow.innerHTML = timeRemainMin + ":" + timeRemainSec;
	}
}
</script>


{% endblock %}

onlineAuction/portal/templates/portal/activeArticles.html
{% extends 'portal/base.html' %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />
{% block content %}

<div class = "container">
    <div id= "header">
        <h1>ACTIVE ARTICLES</h1>
    </div>
<div  id="tablearticle">
<table>
    <tr>
        <th>Start Bid</th>
        <th>Article Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>Minimum Bid</th>
        <th>Image</th>

    </tr>
{% for item in active %}

    <tr>
    <td><a href="BidPage/{{item.id}}">Bid on this</a></td>
        <td>{{ item.articlename}}</td>
        <td>{{ item.category }}</td>
        <td>{{ item.desc }}</td>
        <td>{{ item.minbid}}</td>
        <td><img src="{% static 'portal/article_images/'%}{{item.articleimage_set.reverse.0}}" alt="Image"></td>

     </tr>
{% endfor %}
</table>
</div>
{% endblock %}

onlineAuction/portal/templates/portal/adminPage.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />

{% if messages %}
    <div id="message">
{% for message in messages %}
   <h3> {{ message }}</h3>
{% endfor %}
    </div>
{% endif %}
<div>
				<div id = "top">
					<h1 style = "text-align:center">
					ADMIN PORTAL
					</h1>
					<h3>Welcome Admin</h3>
				</div>


				<div id = "navigate">
					<h4 align = "center">JUMP TO</h4>

					<ul>
					<li><a class = "try" href="{% url 'portal:adminPage' %}"><b>Home</b></a></li>
                     <li><a class = "try" href="{% url 'signup:logout' %}"><b>LOGOUT</b></a></li>

					</ul>
				</div>
</div>


<div  id="table">
<table>
    <tr>
        <th>Username</th>
        <th>Name</th>
    </tr>
    {% for item in details %}
    <tr> 
        <td>{{ item.userName }}</td>
        <td>{{ item.name }}</td>
        <td>
           <a href="showArticles/{{item.id}}">Show Articles</a>
         </td>
        <td>
           <a href="delete/{{item.id}}">Delete</a>
         </td>
        <td>
           <a href="ban/{{item.id}}">Ban</a>
        </td>
     </tr>
    {% endfor %}
</table>
</div>

onlineAuction/portal/templates/portal/adminPageShowArticles.html
{% load static %}

{% if messages %}
    <div id="message">
{% for message in messages %}
   <h3> {{ message }}</h3>
{% endfor %}
    </div>
{% endif %}
<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />
<div>
				<div id = "top">
					<h1 style = "text-align:center">
					ADMIN PORTAL
					</h1>
					<h3>Welcome Admin</h3>
				</div>


				<div id = "navigate">
					<h4 align = "center">JUMP TO</h4>

					<ul>
					<li><a class = "try" href="{% url 'portal:adminPage' %}"><b>Home</b></a></li>

                    <li><a class = "try" href="{% url 'signup:logout' %}"><b>LOGOUT</b></a></li>

					</ul>
				</div>
</div>

<div  id="tablearticle">
<table>
    <tr>
        <th>Delete Article</th>
        <th>Article Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>Minimum Bid</th>
        <th>Image</th>

    </tr>
    {% for item in details %}
    <tr>
    <td><a href="showArticles/{{ item.userid }}/deleteArticle/{{item.id}}">Delete</a></td>
        <td>{{ item.articlename}}</td>
        <td>{{ item.category }}</td>
        <td>{{ item.desc }}</td>
        <td>{{ item.minbid}}</td>
        <td><img src="{% static 'portal/article_images/'%}{{item.articleimage_set.reverse.0}}" alt="Image"></td>

     </tr>
    {% endfor %}
</table>
</div>

onlineAuction/portal/templates/portal/admin_page.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />
<div  id="table">
<table>
    <tr>
        <th>Username</th>
        <th>Name</th>
    </tr>
    {% for item in details %}
    <tr> 
        <td>{{ item.userName }}</td>
        <td>{{ item.name }}</td>
        <td>
            
           <a href="delete/{{item.id}}">Delete</a>
            
            
        </td>
     </tr>
    {% endfor %}
</table>
</div>

onlineAuction/portal/templates/portal/articleForm.html
{% extends 'portal/base.html' %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />



{% block content %}
<div class = "container">
	<div id= "header">
		<h1>ARTICLE REGISTER</h1>
	</div>
	<form enctype="multipart/form-data" method="post">
		{% csrf_token %}
		<div class = "forms">
			<table id = "try">
				{{form}}
				<tr><td id="sub" colspan = "2" align="center"><input type="submit" value="Submit" /></td></tr>
				<tr><td id = "msg" colspan = "6" style = "color:red;"></td></tr>
			</table>
		
		</div>

	</form>

</div>


<script type="text/javascript">
	
var x = document.getElementById("id_private");
hide(x);
function checkHigest(ele)
{	
	var btn = document.getElementById("sub");
	var msg = document.getElementById("msg");
	if(ele.value <= 0)
	{
		btn.disabled = true;
		msg.innerHTML = "min bid should be more 0";
	}
	else
	{
		btn.disabled = false;
		msg.innerHTML = ""
	}
}

function hide(ele)
{
	var list = document.getElementById("id_Select_Users");
	list.style.listStyle="none"
	if(ele.checked == true)
	{
		list.style.display = "block";
	}
	else
	{
		list.style.display = "none";
	}
}


</script>
{% endblock %}

onlineAuction/portal/templates/portal/base.html
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />

{% if messages %}
    <div id="message">
{% for message in messages %}
   <h3> {{ message }}</h3>
{% endfor %}
    </div>
{% endif %}


<div id = "top">
	<h1 style = "text-align:center">
	USER PORTAL
	</h1>
	<h1><a class = "try" href = "{% url 'portal:index' %}">Welcome {{userName}}</a></h1>
</div>

{% block content %}

{% endblock %}



<div>


				<div id = "navigate">
					<h4 align = "center">JUMP TO</h4>
					
					<ul>
					<li><a class = "try" href="{% url 'portal:RegForm' %}"><b>ADD ARTICLE</b></a></li>
					<li><a class = "try" href="{% url 'signup:VisaForm' %}"><b>VISA REGISTER</b></a></li>
					<li><a class = "try" href="{% url 'portal:userArticles' %}"><b>ARTICLES</b></a></li>
					<li><a class = "try" href="{% url 'portal:activeArticles' %}"><b>ACTIVE ARTICLES</b></a></li>
                    <li><a class = "try" href="{% url 'portal:recentArticles' %}"><b>RECENT ARTICLES</b></a></li>
                    <li><a class = "try" href="{% url 'portal:soldArticles' %}"><b>SOLD ARTICLES</b></a></li>
					<li><a class = "try" href="{% url 'portal:wonArticles' %}"><b>WON ARTICLES</b></a></li>
					<li><a class = "try" href="{% url 'signup:logout' %}"><b>LOGOUT</b></a></li>
					
					</ul>
				</div>
</div>

onlineAuction/portal/templates/portal/editArticleForm.html
{% extends 'portal/base.html' %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'portal/main.css' %}" />



{% block content %}
<div class = "container">
	<div id= "header">
		<h1>ARTICLE REGISTER</h1>
	</div>
	<form enctype="multipart/form-data" method="post">
		{% csrf_token %}
		<div class = "forms">
			<table id = "try">
				{{form}}
				<tr><td colspan = "2" align="center"><input type="submit" value="Submit" /></td></tr>
			</table>
		
		</div>

	</form>

</div>

{% endblock %}